### ISSUE TITLE
Evaluate

### ISSUE THREAD

**Issue by Yangr116** [CR-Gjx/Img2Prompt#1]
evaluation code?

**Comment by CR-Gjx** [comment]
Hello, Thanks for the interest in the paper. I am quite busy these months, and I will public the evaluation code next week

**Comment by Yangr116** [comment]
Thanks!

**Comment by CR-Gjx** [comment]
Hi,  I have uploaded the evaluation codes. Please do not hesitate to contact me if you come across some problems.
