### ISSUE TITLE
Hello, I ran the run_okvqa.sh file error

### ISSUE THREAD

**Issue by QingWind6** [CR-Gjx/Img2Prompt#2]
FileNotFoundError: [Errno 2] No such file or directory: '../annotation_new/mscoco_val2014_annotations.json'

How can I solve this problem? thank you！

**Comment by CR-Gjx** [comment]
Hi, you can find it in [https://cocodataset.org/#download](url). Thanks! I will update it in ReadMe

**Comment by QingWind6** [comment]
Thanks for your reply, but I downloaded the file 2014 Train/Val annotations [241MB] and found that there is no json file with the same name as the following: 
mscoco_val2014_annotations.json and OpenEnded_mscoco_val2014_questions.json

Do I need to rename the file or do related processing? Thank you!

**Comment by CR-Gjx** [comment]
As you can see in the log file, the names are the same, so do not need to rename it. Thank you!
If you have further questions, please contact me

**Comment by QingWind6** [comment]
Hello, what should I do if the following error occurs after I run the script? Thank you!



2023-05-15 20:30:27,249 - INFO - train -   Generate VQA test result:  [5045/5046]  eta: 0:00:00    time: 0.2627  data: 0.0000  max mem: 14169
2023-05-15 20:30:27,249 - INFO - train -   Generate VQA test result: Total time: 0:22:16 (0.2649 s / it)
save results
result file saved to ./output_new/vqa_result/result/_okvqa_opt-6.7b_huggingcaps30_question30_questiontype_g_q.json
Training time 0:22:34
Loading and preparing results...     
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/jojang/Documents/Img2Prompt/VL_captioning/Imape2Prompt_evaluation.py:575 in       │
│ <module>                                                                                         │
│                                                                                                  │
│   572 │   yaml.dump(config, open(os.path.join(args.output_dir, 'config.yaml'), 'w'))             │
│   573 │   logger, writer = utils.setup_default_logging(args)                                     │
│   574 │   # args.rsl_csv = os.path.join('./csv_folder', args.rsl_csv)                            │
│ ❱ 575 │   main(args, config, logger, writer)                                                     │
│   576                                                                                            │
│                                                                                                  │
│ /home/jojang/Documents/Img2Prompt/VL_captioning/Imape2Prompt_evaluation.py:461 in main  │
│                                                                                                  │
│   458 │   │                                                                                      │
│   459 │   │   rsl_csv_file = os.path.join(args.result_dir, '%s.csv' % rsl_csv_filename)          │
│   460 │   │   if not args.test_server:                                                           │
│ ❱ 461 │   │   │   vqaEval = vqa_eval(vqa, result_file, config['val_ques_path'], logger=logger,   │
│   462 │   │   │   rsl['overall_acc'] = vqaEval.accuracy['overall']                               │
│   463 │   │   │   if 'other' in vqaEval.accuracy['perAnswerType'].keys():                        │
│   464 │   │   │   │   rsl['other'] = vqaEval.accuracy['perAnswerType']['other']                  │
│                                                                                                  │
│ /home/jojang/Documents/Img2Prompt/VL_captioning/dataset/utils.py:375 in vqa_eval        │
│                                                                                                  │
│   372                                                                                            │
│   373 def vqa_eval(vqa, result_file, test_ques_path, logger=None, n=2, dataset='vqa'):           │
│   374 │                                                                                          │
│ ❱ 375 │   vqaRes = vqa.loadRes(result_file, test_ques_path)                                      │
│   376 │   # create vqaEval object by taking vqa and vqaRes                                       │
│   377 │   vqaEval = VQAEval(vqa, vqaRes, n=n)  # n is precision of accuracy (number of places    │
│   378 │   # evaluate results                                                                     │
│                                                                                                  │
│ /home/jojang/Documents/Img2Prompt/VL_captioning/vqaTools/vqa.py:163 in loadRes          │
│                                                                                                  │
│   160 │   │   anns    = json.load(open(resFile))                                                 │
│   161 │   │   assert type(anns) == list, 'results is not an array of objects'                    │
│   162 │   │   annsQuesIds = [ann['question_id'] for ann in anns]                                 │
│ ❱ 163 │   │   assert set(annsQuesIds) == set(self.getQuesIds()), \                               │
│   164 │   │   'Results do not correspond to current VQA set. Either the results do not have pr   │
│   165 │   │   for ann in anns:                                                                   │
│   166 │   │   │   quesId               = ann['question_id']                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: Results do not correspond to current VQA set. Either the results do not have predictions for all question ids in annotation file or there is atleast one question id that does not 
belong to the question ids in the annotation file.

**Comment by QingWind6** [comment]
Hello, I have found the file I need to run the code. In addition, I also want to know whether using only a 4090 video card can complete the experiment except 175B OPT?

**Comment by CR-Gjx** [comment]
Hi, LLM normally takes 2 times GPU memory than its parameter size, e.g. 13B OPT will occupy 26GB GPU memory.
